### ISSUE TITLE
Bug: format video description returned from api's into html to render the correct line breaks

### ISSUE THREAD

**Issue by isabellatea** [eureka-io/MindFeed#149]
current returning as giant blobs of text

**Comment by Vasanthkesavan** [comment]
Server can make api calls and respond to the client, I think formatting the text(/n, /r) is dependent on what type of operating system we use and I think it should be processed in the client side.

**Comment by isabellatea** [comment]
I will make admin panel be able to edit description to cut it down characters. I'll also see if the edit can save html to incorporate the formatting
